# Site settings
title: Coded By Khaya
header-img: img/home-bg.png
email: yahyal0v3@yahoo.com
copyright_name: yahyal0v3
description: > # this means to ignore newlines until "baseurl:"
  The Adventures of a Creative Writer's Journey to Becoming a Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yahyal0v3
learn_profile: yahyal0v3
email_username: yahyal0v3@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
